### ISSUE TITLE
Main Todo 

### ISSUE THREAD

**Issue by arjunkalburgi** [askalburgi/helpmesee#1]
- [ ] Get the pi to take pictures and test the new 1m cable
- [ ] Vision API - Get Google's API to recognize the pictures
- [ ] Speak return to user.
- [ ] Make glasses
